services:
  db:
    image: postgres:17.5-alpine
    environment:
      POSTGRES_DB: Online_Store
      POSTGRES_USER: soheilk
      POSTGRES_PASSWORD: soheilk123
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7.4.0-alpine

  web:
    build: .
    volumes:
      - shared:/shared
    depends_on:
      - db
      - redis
    env_file:
      - .env

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - shared:/shared
    depends_on:
      - web

volumes:
  pgdata:
  shared:

